### ISSUE TITLE
Automatic built releases

### ISSUE THREAD

**Issue by lutostag** [MadBomber/justprep#5]
Hey @MadBomber. First off wanted to say thanks for working on a great project!

Appreciate you thinking about how to `include` other justfiles in a clean way that is usable right now!

I've been using it for a while now for my personal projects -- but some folks I have been talking with about `justprep` have a hard time to install it.

Would you be interested if I setup some automatic github actions to build binaries for folks (starting with the crystal one) whenever you cut a new release?

I would like to help out if possible, but first `just` :wink: wanted to check if that was something you would appreciate!

If not that is fine too. Appreciate your work!

**Comment by MadBomber** [comment]
@lutostag  great idea.  I have not taken the time to learn any of the actions/release features that GH offers.  Your idea is good.  How shall we proceed?

**Comment by lutostag** [comment]
I am gonna try to follow along with the docs laid out at https://crystal-lang.org/reference/1.3/guides/ci/gh-actions.html in a fork, and can submit a PR if that is helpful.

Gonna see how far I get this weekend! Happy to chat/pair with you on it if you want -- I will be hanging around in the `just` discord at https://discord.gg/ezYScXR

**Comment by lutostag** [comment]
I think I got it working with #6 -- but happy to chat with you on any questions you might have (either in this thread or PR or channel above). Or if its not something you are interested in that is fine as well.

Thanks again for a great project! Appreciate your work on making justfiles easier to compose!

**Comment by MadBomber** [comment]
Greg I am away on a short family road trip. I will be back home later tonight will catch up with you then. Thank you for taking on this enhancement. 

Dewayne
   o-*

**Comment by MadBomber** [comment]
Greg I merged the release then  updated the README file and bumped the version number.

**Comment by MadBomber** [comment]
I see that the workflow ran after I manually told github to build a release but I do not see the links anywhere to download the binary.

**Comment by lutostag** [comment]
The links are in the "assets" section of the release at the bottom.

![IMG_20220319_203637](https://user-images.githubusercontent.com/962625/159144362-69561bb3-250b-44dc-9d79-d3e65fb0de22.jpg)

They should run automatically whenever you add a new git tag. I'm also looking into seeing if I can add it via a homebrew tap -- but not sure how feasible it is. Haven't written a formula for brew before.

I appreciate the merge! Does it work like you would want? I could also try writing up some more in the README too if that would be helpful.

**Comment by lutostag** [comment]
https://github.com/lutostag/justprep/releases/latest

Should be the link to the latest "release" where the binaries can be found in the assets section.
